# Javascript Node CircleCI 2.0 configuration file
# Configuration reference: https://circleci.com/docs/2.0/configuration-reference/
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      ignore:
        - /^wip-.*$/
        - /^.*-wip$/
    docker:
      # Available images are listed at https://github.com/circleci-public/circleci-dockerfiles
      - image: circleci/node:12.13.0

    working_directory: ~/repo

    steps:
      # Check out the branch
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: 'Install dependencies'
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: 'Compile'
          command: yarn build

      - run:
          name: 'Check types'
          command: yarn check-types

      - run:
          name: 'Run tests'
          command: yarn test
