name: Check code

on:
  push:
    branches-ignore:
      - 'wip-**'
      - '**-wip'
      - 'master'
      - 'alpha'
      - 'beta'
      - 'next'

jobs:
  check-code:
    name: Typecheck, lint, test & build

    env:
      CI: true
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      CI_NEEDS_GIT_HISTORY: ${{ secrets.CI_NEEDS_GIT_HISTORY }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch
        run: |
          if -z "${CI_NEEDS_GIT_HISTORY}"; then
            git fetch --prune --unshallow && git fetch origin 'master:master'
          fi
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
          yarn install --frozen-lockfile --production=false
      - name: Check types
        run: yarn run typecheck
      - name: Lint
        run: yarn run lint --no-cache --quiet
      - name: Test
        run: yarn test
      - name: Build
        run: yarn run build
