name: Check code

on:
  push:
    branches-ignore:
      - 'wip-**'
      - '**-wip'
      - 'main'
      - 'alpha'
      - 'beta'
      - 'next'

jobs:
  check-code:
    name: Typecheck, lint, test & build

    env:
      CI: true
      NPM_READ_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN || secrets.NPM_READ_AND_PUBLISH_TOKEN || secrets.NPM_READ_TOKEN }}
      STABLE_RELEASE_BRANCH: 'main'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch
        run: git fetch --prune --unshallow && git fetch origin "$STABLE_RELEASE_BRANCH:$STABLE_RELEASE_BRANCH"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_READ_TOKEN" > .npmrc
          yarn install --frozen-lockfile --production=false
          yarn add @skypilot/quick-release --production=false
      - name: Check types
        run: yarn run typecheck
      - name: Lint
        run: yarn run lint --no-cache --quiet
      - name: Test
        run: yarn test
      - name: Build
        run: |
          if [[ $(yarn --silent spqr-option 'code-check.build') != 'false' ]] ; then
            yarn run build
          fi
