name: Stable release

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '*.md'
      - 'LICENSE'
      - 'package.json'

jobs:
  stable-release:
    name: Create stable release

    env:
      BOT_EMAIL: ${{ secrets.SP_BOT_EMAIL || 'repo-bot@users.noreply.github.com' }}
      BOT_NAME: ${{ secrets.SP_BOT_NAME || 'repo-bot' }}
      CI: true
      GPG_KEY: ${{ secrets.SP_BOT_GPG_KEY }}
      GPG_KEY_ID: ${{ secrets.SP_BOT_GPG_KEY_ID }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      SP_RELEASE_TOKEN: ${{ secrets.SP_RELEASE_TOKEN }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SP_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Fetch
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
          yarn install --frozen-lockfile --production=false
          yarn add @skypilot/bump-version conventional-changelog-cli@2 finepack@2
          git checkout -- .
      - name: Lint config files
        run: yarn --silent finepack
      - name: Gather published versions
        run: |
          mkdir -p local
          yarn info --silent . versions > local/published-versions.txt
      - name: Bump version
        if: success()
        run: |
          yarn --silent bump-version && yarn --silent conventional-changelog -p angular -r 0 > CHANGELOG.md
      - name: Publish
        if: success()
        run: |
          if test -n "$NPM_AUTH_TOKEN" ; then
            yarn config set //registry.yarnpkg.com/:_authToken=$NPM_AUTH_TOKEN
            yarn run publish:default
          else
            echo "No NPM_AUTH_TOKEN found. Skipping publication"
          fi
      - name: Configure identity
        if: success()
        run: |
          git config --global user.email $BOT_EMAIL
          git config --global user.name $BOT_NAME
          if test -n "$GPG_KEY" && test -n "$GPG_KEY_ID"; then
            echo "$GPG_KEY" | base64 -d > private.key
            gpg --import ./private.key
            rm ./private.key
            git config --global commit.gpgsign true
            git config --global tag.gpgsign true
            git config --global user.signingkey $GPG_KEY_ID
          fi
      - name: Commit files
        if: success()
        run: |
          git add package.json CHANGELOG.md
          git commit --message "Release $(yarn --silent get-current-version)"
      - name: Tag
        if: success()
        run: |
          git tag -a v$(yarn --silent get-current-version) -m "Release $(yarn --silent get-current-version)"
      - name: Push changes
        if: success()
        run: git push --tags origin $(git symbolic-ref --short HEAD)
