name: Prerelease

on:
  push:
    branches:
      - 'alpha'
      - 'beta'
      - 'next'
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'LICENSE'
      - 'package.json'

jobs:
  prerelease:
    name: Create prerelease

    env:
      CI: true
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SP_RELEASE_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Fetch
        run: |
          git fetch --prune --unshallow
          git fetch origin 'master:master'
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
          yarn install --frozen-lockfile --production=false
          yarn add @skypilot/bump-version conventional-changelog-cli@2 finepack@2
          git checkout -- .
      - name: Bump version
        if: success()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name ${GITHUB_ACTOR}
          yarn --silent bump-version
      - name: Publish
        if: success()
        run: |
          if test -n "$NPM_AUTH_TOKEN" ; then
            yarn config set //registry.yarnpkg.com/:_authToken=$NPM_AUTH_TOKEN
            yarn run publish:default --tag $(git symbolic-ref --short HEAD)
          else
            echo "No NPM_AUTH_TOKEN found. Skipping publication"
          fi
      - name: Tag
        if: success()
        run: |
          git tag -a v$(yarn --silent get-current-version) -m "Prerelease $(yarn --silent get-current-version)"
      - name: Push tag
        if: success()
        run: git push --tags
