name: Publish NPM package

on:
  push:
    branches:
      - 'master'
    paths:
      - 'CHANGELOG.md'

jobs:
  publish:
    name: Build & publish

    env:
      CI: true
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
          yarn install --frozen-lockfile --production=false
      - name: Publish
        run: |
          yarn config set //registry.yarnpkg.com/:_authToken=$NPM_AUTH_TOKEN
          yarn run publish:default
