name: Build & test NPM package

on:
  push:
    branches-ignore:
      - 'wip-**'
      - '**-wip'
      - 'master'

jobs:
  build:
    name: Typecheck, lint, test & build

    env:
      CI: true
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
          yarn install --frozen-lockfile --production=false
      - name: Check types
        run: yarn run typecheck
      - name: Lint
        run: yarn run lint --no-cache --quiet
      - name: Test
        run: yarn test
      - name: Build
        run: yarn run build
