name: Node CI

on:
  push:
    branches-ignore:
      - 'wip-**'
      - '**-wip'

jobs:
  build:
    name: Build, lint & test

    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install --frozen-lockfile --production=false
      - name: Check types
        run: yarn run check-types
      - name: Lint
        run: yarn run lint --no-cache --quiet
      - name: Test
        run: yarn test
      - name: Build
        run: yarn run build
